#!/usr/bin/env python3
"""Generate local MiSans WOFF2 shards without dropping supported characters.
Usage: python scripts/subset-misans.py /path/to/official/MiSans.zip
Requires: pip install 'fonttools[woff]==4.64.0'
"""
from pathlib import Path
from io import BytesIO
import concurrent.futures
import hashlib
import json
import sys
import zipfile
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'public/fonts/misans'
WEIGHTS = {'Regular': 400, 'Semibold': 600, 'Bold': 700}


def ranges(points):
    spans = []
    for point in sorted(points):
        if spans and point == spans[-1][1] + 1:
            spans[-1][1] = point
        else:
            spans.append([point, point])
    return ','.join(f'U+{a:X}' if a == b else f'U+{a:X}-{b:X}' for a, b in spans)


def generate(item):
    weight, data = item
    original = TTFont(BytesIO(data))
    supported = set(original.getBestCmap())
    # Latin and punctuation are tiny and are all the English homepage needs.
    latin = {c for c in supported if c < 0x300 or 0x2000 <= c <= 0x206F or c == 0x20AC}
    # Keep each remaining shard bounded, including rare and supplementary CJK.
    rest = sorted(supported - latin)
    groups = [('latin', latin)] + [(f'{i//512:03}', set(rest[i:i+512])) for i in range(0, len(rest), 512)]
    rules = []
    seen = set()
    for name, chars in groups:
        font = TTFont(BytesIO(data))
        options = subset.Options()
        options.flavor = 'woff2'
        options.layout_features = ['*']
        options.name_IDs = ['*']
        options.name_legacy = True
        options.name_languages = ['*']
        subsetter = subset.Subsetter(options=options)
        subsetter.populate(unicodes=chars)
        subsetter.subset(font)
        font.flavor = 'woff2'
        filename = f'MiSans-{weight}-{name}.woff2'
        target = OUT / filename
        font.save(target)
        actual = set(TTFont(target).getBestCmap())
        assert actual == chars, (filename, chars - actual)
        assert not (seen & actual)
        seen |= actual
        rules.append(f'''@font-face {{
  font-family: "MiSans";
  src: url("/fonts/misans/{filename}") format("woff2");
  font-weight: {WEIGHTS[weight]};
  font-style: normal;
  font-display: swap;
  unicode-range: {ranges(chars)};
}}''')
    assert seen == supported
    print(f'{weight}: verified all {len(seen)} Unicode characters across {len(groups)} shards', flush=True)
    return '\n\n'.join(rules), {'weight': weight, 'characters': len(seen), 'shards':len(groups),'source_sha256':hashlib.sha256(data).hexdigest()}


if __name__ == '__main__':
    archive = zipfile.ZipFile(sys.argv[1])
    OUT.mkdir(parents=True, exist_ok=True)
    items = [(w, archive.read(f'MiSans/woff2/MiSans-{w}.woff2')) for w in WEIGHTS]
    with concurrent.futures.ProcessPoolExecutor(max_workers=3) as pool:
        results = list(pool.map(generate, items))
    (ROOT / 'src/styles/misans.css').write_text('/* Generated by scripts/subset-misans.py. Preserve the full Unicode coverage. */\n'+ '\n\n'.join(r[0] for r in results)+'\n')
    (OUT/'manifest.json').write_text(json.dumps([r[1] for r in results], indent=2)+'\n')
